### PR TITLE
Allow provider configuration api_url and custom_app_url to be set from environment variables

### PR DESCRIPTION
**Pull request by pdecat**
The goal is to allow running acceptance tests against the eu0 realm.

### CODE REVIEW

**Review by cory-signalfx — APPROVED** [review]
This looks good to me! Does this being a draft mean you wanna add some more stuff? Lemme know, and I'll wait or merge. :)

**Comment by pdecat** [comment]
Well, I'm facing crashes when running acceptance tests right now:

```
# set|grep SFX
SFX_API_URL=https://api.eu0.signalfx.com
SFX_AUTH_TOKEN=******
SFX_CUSTOM_APP_URL=https://******.signalfx.com

# TF_LOG=debug make testacc TESTARGS='-run=TestAccCreateUpdateIntegrationGCP -count=1'
...
--- FAIL: TestAccCreateUpdateIntegrationGCP (0.67s)
panic: interface conversion: interface {} is nil, not string [recovered]
        panic: interface conversion: interface {} is nil, not string

goroutine 21 [running]:
testing.tRunner.func1.1(0x1198920, 0xc0005a6ff0)
        /usr/local/go/src/testing/testing.go:940 +0x2f5
testing.tRunner.func1(0xc0004fc360)
        /usr/local/go/src/testing/testing.go:943 +0x3f9
panic(0x1198920, 0xc0005a6ff0)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/terraform-providers/terraform-provider-signalfx/signalfx.testAccCheckIntegrationGCPResourceExists(0xc00046d490, 0x0, 0x0)
        /home/patrick/go/src/github.com/terraform-providers/terraform-provider-signalfx/signalfx/resource_signalfx_gcp_integration_test.go:92 +0x3e2
github.com/hashicorp/terraform-plugin-sdk/helper/resource.testStep(0xc0005808f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/patrick/go/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing_config.go:109 +0xe89
github.com/hashicorp/terraform-plugin-sdk/helper/resource.testStepConfig(...)
        /home/patrick/go/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing_config.go:27
github.com/hashicorp/terraform-plugin-sdk/helper/resource.Test(0x16464e0, 0xc0004fc360, 0x0, 0xc000461890, 0xc0004fa360, 0x0, 0x0, 0x1380fe8, 0xc0004ab900, 0x3, ...)
        /home/patrick/go/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing.go:648 +0x1569
github.com/terraform-providers/terraform-provider-signalfx/signalfx.TestAccCreateUpdateIntegrationGCP(0xc0004fc360)
        /home/patrick/go/src/github.com/terraform-providers/terraform-provider-signalfx/signalfx/resource_signalfx_gcp_integration_test.go:54 +0x2d2
testing.tRunner(0xc0004fc360, 0x1380990)
        /usr/local/go/src/testing/testing.go:991 +0xdc
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1042 +0x357
FAIL    github.com/terraform-providers/terraform-provider-signalfx/signalfx     0.690s
?       github.com/terraform-providers/terraform-provider-signalfx/version      [no test files]
FAIL
make: *** [GNUmakefile:17: testacc] Error 1
```

**Comment by pdecat** [comment]
Pushed a fix for this crash in #212

**Comment by cory-signalfx** [comment]
Ha, looks like you saw the answer as quick as I did. 😸 (the id nil thing)

**Comment by pdecat** [comment]
I'm getting 401 errors now, I think the provider initialization is not working as I expect it with my new environment variables.

**Comment by pdecat** [comment]
Alright, the provider is ok, it's just the client created in the acceptance test that need updating too:

```
	client, _ := sfx.NewClient(os.Getenv("SFX_AUTH_TOKEN"))
```

https://github.com/pdecat/terraform-provider-signalfx/blob/1f0873f7b428a8166a56ab50a757924c51615367/signalfx/resource_signalfx_gcp_integration_test.go#L96-L97

**Comment by cory-signalfx** [comment]
Exciting!

**Comment by pdecat** [comment]
This now works as expected and is ready for re-review.

**Pull request merged**
