### PR TITLE
added time zone property to detector

### PR DESCRIPTION
**Pull request by rajeshkurup**

### CODE REVIEW

**Comment by rajeshkurup** [comment]
@keitwb Hi, please review and approve this PR (related to Detector Time Zone improvement submitted to signalfx-go)
thanks!

**Review by keitwb — APPROVED** [review]

**Comment by rajeshkurup** [comment]
@keitwb Thanks for approving this PR!
Can you please release it? I'm kind of blocked on the deliverables of this sprint.

**Comment by keitwb** [comment]
Yes, @jrcamp will do it soon.

**Comment by rajeshkurup** [comment]
thanks @keitwb - it is 6.6.0 right?

**Comment by keitwb** [comment]
Yes

**Pull request merged**
