### PR TITLE
FFM-1082 Update with tag 1.40.1 for signalfx-go and update for stopTime

### PR DESCRIPTION
**Pull request by pdoshisplunk**

### CODE REVIEW

**Comment by pdoshisplunk** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by pdoshisplunk** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by echoi-splk — APPROVED** [review]
LGTM

**Comment by pdoshisplunk** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by atoulme** [comment]
recheck

**Pull request merged**
