### PR TITLE
Rename dashboard ID in data link

### PR DESCRIPTION
**Pull request by cory-signalfx**
It was suggested this would be more user friendly!

### CODE REVIEW

**Comment by saikrishna547** [comment]
Hi when i add this code I got the following Errors not sure why, let me know if i am missing anything 

resource "signalfx_data_link" "mydatalink_overview_1" {
        dashboard_id = "${signalfx_dashboard.overview.id}"
    property_name = "AWSUniqueId"
    target_signalfx_dashboard {
      is_default = true
      name = "Overview AWS_UniqueID data link to host dashboard"
            dashboard_group_id = "${signalfx_dashboard_group.mdcat_dashboard_group.id}"
            context_dashboard_id = "${signalfx_dashboard.host.id}"
    }
}
on datalinks.tf line 4, in resource "signalfx_data_link" "mydatalink_overview_1":
   4:         dashboard_id = "${signalfx_dashboard.overview.id}"

An argument named "dashboard_id" is not expected here.


Error: Missing required argument

  on datalinks.tf line 6, in resource "signalfx_data_link" "mydatalink_overview_1":
   6:     target_signalfx_dashboard {

The argument "dashboard_id" is required, but no definition was found.


Error: Unsupported argument

  on datalinks.tf line 10, in resource "signalfx_data_link" "mydatalink_overview_1":
  10:             context_dashboard_id = "${signalfx_dashboard.host.id}"

An argument named "context_dashboard_id" is not expected here.

**Comment by cory-signalfx** [comment]
Hey @saikrishna547! I believe you have the use of those two properties backward. Try this:

```
resource "signalfx_data_link" "mydatalink_overview_1" {
  context_dashboard_id = "${signalfx_dashboard.overview.id}"
  property_name = "AWSUniqueId"
  target_signalfx_dashboard {
    is_default = true
    name = "Overview AWS_UniqueID data link to host dashboard"
    dashboard_group_id = "${signalfx_dashboard_group.mdcat_dashboard_group.id}"
    dashboard_id = "${signalfx_dashboard.host.id}"
  }
}
```

**Comment by saikrishna547** [comment]
Oh yeah, looks like its working now. Thanks

**Comment by saikrishna547** [comment]
Copied the same still facing issue Says 

Error: Bad status 400: {
  "code" : 400,
  "message" : "Failed to deserialize payload at: sf.domain.crosslink.CrossLink[\"contextId\"]"
}

  on datalinks.tf line 14, in resource "signalfx_data_link" "mydatalink_overview_1":
  14: resource "signalfx_data_link" "mydatalink_overview_1" {

**Comment by saikrishna547** [comment]
Hi @cory-signalfx  The resource is created but the value for Trigger section is empty. Expecting a AWSUniqueId in the trigger section for any of value. Please check the screenshot
[
Screen Shot 2020-02-20 at 6 47 56 PM
](url)

**Comment by saikrishna547** [comment]
Hi @cory-signalfx  The resource is created but the value was empty in the UI section. 
[
Screen Shot 2020-02-20 at 6 47 56 PM
](url)

**Pull request merged**
