### PR TITLE
Bump sfx-go and use namedToken

### PR DESCRIPTION
**Pull request by cory-signalfx**
What is says on the tin!

### CODE REVIEW

**Comment by cory-signalfx** [comment]
cc @yannyu and @tedoc2000

**Comment by pdecat** [comment]
@cory-signalfx now you got me curious, what's that [undocumented](https://github.com/terraform-providers/terraform-provider-signalfx/commit/cb97e758aa7bc5fc4608bc82231fb84ba2cd6a5c) `named_token` argument usage?

I've tried to set it on a GCP integration but always get a 500 error no matter what value I pass:

```
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: 2020/06/03 15:38:07 [DEBUG] SignalFx API Request Details:
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: ---[ REQUEST ]---------------------------------------
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: POST /v2/integration HTTP/1.1
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: Host: api.eu0.signalfx.com
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: User-Agent: Terraform/0.12.25 terraform-provider-signalfx/4.23.0
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: Content-Length: 2630
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: Content-Type: application/json
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: X-Sf-Token: uw******
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: Accept-Encoding: gzip
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4:
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: {
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4:  "enabled": true,
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4:  "name": "GCPIntegration",
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4:  "type": "GCP",
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4:  "pollRate": 300000,
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4:  "projectServiceKeys": [
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4:   {
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4:    "projectId": "******",
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4:    "projectKey": "{\n  \"type\": \"service_account\",\n  \"project_id\": \"******\",\n  \"private_key_id\": \"6d******\",\n  \"private_key\": \"-----BEGIN PRIVATE KEY-----\\nMIIEv****=\\n-----END PRIVATE KEY-----\\n\",\n  \"client_email\": \"monitoring-signalfx@******.iam.gserviceaccount.com\",\n  \"client_id\": \"10******\",\n  \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\n  \"token_uri\": \"https://oauth2.googleapis.com/token\",\n  \"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",\n  \"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/monitoring-signalfx%40******.iam.gserviceaccount.com\"\n}\n"
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4:   }
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4:  ],
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4:  "whitelist": [
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4:   "sfx_env",
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4:   "sfx_monitored"
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4:  ],
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4:  "namedToken": "pdecat"
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: }
2020-06-03T15:38:07.047+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: -----------------------------------------------------
2020-06-03T15:38:07.965+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: 2020/06/03 15:38:07 [DEBUG] SignalFx API Response Details:
2020-06-03T15:38:07.965+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: ---[ RESPONSE ]--------------------------------------
2020-06-03T15:38:07.965+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: HTTP/1.1 500 Internal Server Error
2020-06-03T15:38:07.965+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: Content-Length: 38
2020-06-03T15:38:07.965+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: Cache-Control: no-cache, no-store, must-revalidate, no-transform
2020-06-03T15:38:07.965+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: Connection: keep-alive
2020-06-03T15:38:07.965+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: Content-Type: application/json
2020-06-03T15:38:07.965+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: Date: Wed, 03 Jun 2020 13:38:07 GMT
2020-06-03T15:38:07.965+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: Expires: 0
2020-06-03T15:38:07.965+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: Strict-Transport-Security: max-age=7776000
2020-06-03T15:38:07.965+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: X-Content-Type-Options: nosniff
2020-06-03T15:38:07.965+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4:
2020-06-03T15:38:07.965+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: {
2020-06-03T15:38:07.965+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4:   "code" : 500,
2020-06-03T15:38:07.965+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4:   "message" : null
2020-06-03T15:38:07.965+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: }
2020-06-03T15:38:07.965+0200 [DEBUG] plugin.terraform-provider-signalfx_v4.23.0_x4: -----------------------------------------------------
2020/06/03 15:38:07 [DEBUG] module.signalfx.module.signalfx-integration-cloud-gcp.signalfx_gcp_integration.gcp_claranet_integration: apply errored, but we're indicating that via the Error pointer rather than returning it: Unexpected status code: 500: {
  "code" : 500,
  "message" : null
}
```

Is that because I'm in the EU realm? Or is it something in closed beta?

**Comment by cory-signalfx** [comment]
I don't _think_ it's anything to do with the EU realm.

The named token param is a way of assigning the metrics collected via this integration to a specific token. Does a token with that name exist in your list of tokens?

**Comment by pdecat** [comment]
Oh, nice! It works with an existing access token. I believe that's going to be very helpful to distinguish hosts/metrics counts across monitored environments (e.g. staging, preprod, prod).

**Pull request merged**
