### PR TITLE
Add support for GCP Compute Metadata Whitelist

### LINKED ISSUE #210: Add support for GCP integration whitelist
Hi,

it would be awesome if the SignalFx terraform provider added support for the GCP integration `whitelist` property:

https://github.com/signalfx/signalfx-go/blob/v1.6.37/integration/model_gcp_integration.go#L35

This allows to add metadata to the Compute Engine instance integration:

> `metadata` ** | `gcp_metadata_<metadata-key>` | custom metadata key for the instance (generated based on whitelisted properties specified when completing the integration in SignalFx)

https://docs.signalfx.com/en/latest/integrations/google-cloud-platform.html#compute-engine-instance

image

### PR DESCRIPTION
**Pull request by pdecat**
Resolves #210

### CODE REVIEW

**Comment by cory-signalfx** [comment]
Hey @pdecat, thanks!

This looks to be the start of a patch, as it will need to be folded into the structure sent downstream. Would you like me to take over from here?

**Comment by pdecat** [comment]
Hi Cory, I'm used to do terraform provider development, it's just that I'm struggling to run acceptance tests against the eu0 realm in which our accounts are, hence https://github.com/terraform-providers/terraform-provider-signalfx/pull/213.

**Comment by cory-signalfx** [comment]
Gotya! Left you a question there since that PR is draft mode. Happy to merge it when you are ready. (Also thanks for #211!)

**Comment by pdecat** [comment]
@cory-signalfx regarding the following comment:

```
	// Note that the API doesn't return the project keys so we ignore them,
	// because there's not much reason to poke at just the project id.
```

https://github.com/terraform-providers/terraform-provider-signalfx/pull/212/files#diff-8ca656ed5804cc5475ff61c0ecbd94e4R181

I think it is still worth to process the project ids are those may be changed out of band.

WDYT?

**Comment by cory-signalfx** [comment]
The project IDs are not returned by the API *at all*, so this isn't really a decision we get to make. :(

**Comment by pdecat** [comment]
Yep they are ;)

```
-----------------------------------------------------                                                                                                                                    
2020/05/28 18:16:02 [DEBUG] SignalFx API Request Details:                                                                                                                                
---[ REQUEST ]---------------------------------------                                                                                                                                    
GET /v2/integration/EZHdN82AIAA HTTP/1.1                                                                                                                                                 
Host: api.eu0.signalfx.com                                                                                                                                                               
User-Agent: Terraform/0.12.7-sdk terraform-provider-signalfx/dev                                                                                                                         
Content-Type: application/json                                                                                                                                                           
X-Sf-Token: *****                                                                                                                                                       
Accept-Encoding: gzip                                                                                                                                                                    
                                                                                                                                                                                         
                                                                                                                                                                                         
-----------------------------------------------------                                                                                                                                    
2020/05/28 18:16:02 [DEBUG] SignalFx API Response Details:                                                                                                                               
---[ RESPONSE ]--------------------------------------                                                                                                                                    
HTTP/1.1 200 OK                                                                                                                                                                          
Cache-Control: no-cache, no-store, must-revalidate, no-transform                                                                                                                         
Connection: keep-alive                                                                                                                                                                   
Content-Type: application/json                                                                                                                                                           
Date: Thu, 28 May 2020 16:16:02 GMT                                                                                                                                                      
Expires: 0                                                                                                                                                                               
Strict-Transport-Security: max-age=7776000                                                                                                                                               
Vary: Accept-Encoding, User-Agent                                                                                                                                                        
X-Content-Type-Options: nosniff                                                                                                                                                          
                                                                                                                                                                                         
{                                                                                                                                                                                        
  "created" : 1590682561987,                                                                                                                                                             
  "creator" : "******",                                                                                                                                                             
  "enabled" : false,                                                                                                                                                                     
  "id" : "******",                                                                                                                                                                  
  "lastUpdated" : 1590682561995,                                                                                                                                                         
  "lastUpdatedBy" : "*****",                                                                                                                                                       
  "name" : "GCP - My Team",                                                                                                                                                              
  "pollRate" : 300000,                                                                                                                                                                   
  "projectServiceKeys" : [ {                                                                                                                                                             
    "projectId" : "gcp_project_id_1"                                                                                                                                                     
  }, {                                                                                                                                                                                   
    "projectId" : "gcp_project_id_2"                                                                                                                                                     
  } ],                                                                                                                                                                                   
  "services" : [ "compute" ],                                                                                                                                                            
  "type" : "GCP",                                                                                                                                                                        
  "whitelist" : [ "labels" ]                                                                                                                                                             
}
```

**Comment by cory-signalfx** [comment]
Well! Your patch to the rescue again!

**Comment by cory-signalfx** [comment]
Oh, I misread the comment. It ignores the ids because the *keys* are absent. My bad.

Sure, we can look at them, but adopting a new, changed-out-of-band project id will mean we have no project key in the local state.

**Comment by pdecat** [comment]
That's indeed an issue for new keys added out of band, but:
- we have to reflect the reality anyway,
- it's more about recreating project keys if they were deleted out of band.

**Comment by cory-signalfx** [comment]
Fair enough!

**Comment by pdecat** [comment]
GCP integration whitelist is now functional, please review.

I'll work on `project_service_keys` in another PR.

**Pull request merged**
