### PR TITLE
convert tags from list to set and fix set field

### LINKED ISSUE #304: perpetual diff on tags attribute
Hello @jrcamp @keitwb @asuresh4,

With the last provider version 6.7.4, setting the `tags` attribute to the `signalfx_detector` resource leads to a perpetual diff on terraform plan.

using the example from the official documentation : https://registry.terraform.io/providers/splunk-terraform/signalfx/latest/docs/resources/detector

Here is an example of perpetual change affecting only tags:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # signalfx_detector.application_delay will be created
  + resource "signalfx_detector" "application_delay" {
      + description       = "your application is slow"
      + id                = (known after apply)
      + max_delay         = 30
      + min_delay         = 0
      + name              = " max average delay"
      + program_text      = <<-EOT
            signal = data('app.delay', filter('cluster','test'), extrapolation='last_value', maxExtrapolations=5).max()
            detect(when(signal > 60, '5m')).publish('Processing old messages 5m')
            detect(when(signal > 60, '30m')).publish('Processing old messages 30m')
        EOT
      + show_data_markers = true
      + tags              = [
          + "app-backend",
          + "staging",
        ]
      + time_range        = 3600
      + timezone          = "UTC"
      + url               = (known after apply)

      + rule {
          + description   = "maximum > 60 for 30m"
          + detect_label  = "Processing old messages 30m"
          + disabled      = false
          + notifications = [
              + "Email,foo-alerts@bar.com",
            ]
          + severity      = "Critical"
        }
      + rule {
          + description   = "maximum > 60 for 5m"
          + detect_label  = "Processing old messages 5m"
          + disabled      = false
          + notifications = [
              + "Email,foo-alerts@bar.com",
            ]
          + severity      = "Warning"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

signalfx_detector.application_delay: Creating...
signalfx_detector.application_delay: Creation complete after 2s [id=E4p4_yrAAAA]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
 qmanfroi  ~  tmp  signalfx  terratest  $  4s  
$ terraform apply
signalfx_detector.application_delay: Refreshing state... [id=E4p4_yrAAAA]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # signalfx_detector.application_delay has been changed
  ~ resource "signalfx_detector" "application_delay" {
        id                = "E4p4_yrAAAA"
        name              = " max average delay"
        tags              = []
      + teams             = []
        # (10 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # signalfx_detector.application_delay will be updated in-place
  ~ resource "signalfx_detector" "application_delay" {
        id                = "E4p4_yrAAAA"
        name              = " max average delay"
      ~ tags              = [
          + "app-backend",
          + "staging",
        ]
        # (11 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

signalfx_detector.application_delay: Modifying... [id=E4p4_yrAAAA]
signalfx_detector.application_delay: Modifications complete after 2s [id=E4p4_yrAAAA]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
 qmanfroi  ~  tmp  signalfx  terratest  $  6s  
$ terraform plan
signalfx_detector.application_delay: Refreshing state... [id=E4p4_yrAAAA]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # signalfx_detector.application_delay will be updated in-place
  ~ resource "signalfx_detector" "application_delay" {
        id                = "E4p4_yrAAAA"
        name              = " max average delay"
      ~ tags              = [
          + "app-backend",
          + "staging",
        ]
        # (11 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### PR DESCRIPTION
**Pull request by xp-1000**
fix #304

@jrcamp @keitwb @asuresh4

### CODE REVIEW

**Comment by pdecat** [comment]
Without this change:

```
make testacc TESTARGS='-run=TestAccCreateUpdateDetector -count=1'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccCreateUpdateDetector -count=1 -timeout 120m
?       github.com/splunk-terraform/terraform-provider-signalfx [no test files]
=== RUN   TestAccCreateUpdateDetector
    testing.go:684: Step 0 error: Check failed: Check 5/30 error: signalfx_detector.application_delay: Attribute 'tags.#' expected "2", got "0"
--- FAIL: TestAccCreateUpdateDetector (3.62s)
FAIL
FAIL    github.com/splunk-terraform/terraform-provider-signalfx/signalfx        3.631s
?       github.com/splunk-terraform/terraform-provider-signalfx/version [no test files]
FAIL
make: *** [GNUmakefile:17: testacc] Error 1
```

**Comment by pdecat** [comment]
With this change, it works partly but only one tag is set properly for some test runs:

```
make testacc TESTARGS='-run=TestAccCreateUpdateDetector -count=1'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccCreateUpdateDetector -count=1 -timeout 120m
?       github.com/splunk-terraform/terraform-provider-signalfx [no test files]
=== RUN   TestAccCreateUpdateDetector
    testing.go:684: Step 0 error: After applying this step and refreshing, the plan was not empty:

        DIFF:

        UPDATE: signalfx_detector.application_delay
          description:                  "your application is slow" => "your application is slow"
          disable_sampling:             "false" => "false"
          id:                           "E5CaZOnAEAA" => "E5CaZOnAEAA"
          max_delay:                    "30" => "30"
          min_delay:                    "15" => "15"
          name:                         "max average delay" => "max average delay"
          program_text:                 "signal = data('app.delay').max().publish('app delay')\ndetect(when(signal > 60, '5m')).publish('Processing old messages 5m')\ndetect(when(signal > 60, '30m')).publish('Processing old messages 30m')\n" => "signal = data('app.delay').max().publish('app delay')\ndetect(when(signal > 60, '5m')).publish('Processing old messages 5m')\ndetect(when(signal > 60, '30m')).publish('Processing old messages 30m')\n"
          rule.#:                       "2" => "2"
          rule.0.description:           "maximum > 60 for 30m" => "maximum > 60 for 30m"
          rule.0.detect_label:          "Processing old messages 30m" => "Processing old messages 30m"
          rule.0.disabled:              "false" => "false"
          rule.0.notifications.#:       "1" => "1"
          rule.0.notifications.0:       "Email,foo-alerts@example.com" => "Email,foo-alerts@example.com"
          rule.0.parameterized_body:    "" => ""
          rule.0.parameterized_subject: "" => ""
          rule.0.runbook_url:           "" => ""
          rule.0.severity:              "Critical" => "Critical"
          rule.0.tip:                   "" => ""
          rule.1.description:           "maximum > 60 for 5m" => "maximum > 60 for 5m"
          rule.1.detect_label:          "Processing old messages 5m" => "Processing old messages 5m"
          rule.1.disabled:              "false" => "false"
          rule.1.notifications.#:       "1" => "1"
          rule.1.notifications.0:       "Email,foo-alerts@example.com" => "Email,foo-alerts@example.com"
          rule.1.parameterized_body:    "" => ""
          rule.1.parameterized_subject: "" => ""
          rule.1.runbook_url:           "" => ""
          rule.1.severity:              "Warning" => "Warning"
          rule.1.tip:                   "" => ""
          show_data_markers:            "true" => "true"
          show_event_lines:             "false" => "false"
          tags.#:                       "1" => "2"
          tags.0:                       "tag-2" => "tag-1"
          tags.1:                       "" => "tag-2"
          teams.#:                      "1" => "1"
          teams.0:                      "E5CaatpAIAA" => "E5CaatpAIAA"
          time_range:                   "3600" => "3600"
          timezone:                     "Europe/Paris" => "Europe/Paris"
          url:                          "https://claranet-sandbox.signalfx.com/#/detector/E5CaZOnAEAA" => "https://claranet-sandbox.signalfx.com/#/detector/E5CaZOnAEAA"
          viz_options.#:                "1" => "1"
          viz_options.0.color:          "orange" => "orange"
          viz_options.0.display_name:   "" => ""
          viz_options.0.label:          "app delay" => "app delay"
          viz_options.0.value_prefix:   "" => ""
          viz_options.0.value_suffix:   "" => ""
          viz_options.0.value_unit:     "Second" => "Second"



        STATE:

        signalfx_detector.application_delay:
          ID = E5CaZOnAEAA
          provider = provider.signalfx
          description = your application is slow
          disable_sampling = false
          max_delay = 30
          min_delay = 15
          name = max average delay
          program_text = signal = data('app.delay').max().publish('app delay')
        detect(when(signal > 60, '5m')).publish('Processing old messages 5m')
        detect(when(signal > 60, '30m')).publish('Processing old messages 30m')

          rule.# = 2
          rule.0.description = maximum > 60 for 30m
          rule.0.detect_label = Processing old messages 30m
          rule.0.disabled = false
          rule.0.notifications.# = 1
          rule.0.notifications.0 = Email,foo-alerts@example.com
          rule.0.parameterized_body =
          rule.0.parameterized_subject =
          rule.0.runbook_url =
          rule.0.severity = Critical
          rule.0.tip =
          rule.1.description = maximum > 60 for 5m
          rule.1.detect_label = Processing old messages 5m
          rule.1.disabled = false
          rule.1.notifications.# = 1
          rule.1.notifications.0 = Email,foo-alerts@example.com
          rule.1.parameterized_body =
          rule.1.parameterized_subject =
          rule.1.runbook_url =
          rule.1.severity = Warning
          rule.1.tip =
          show_data_markers = true
          show_event_lines = false
          tags.# = 1
          tags.0 = tag-2
          teams.# = 1
          teams.0 = E5CaatpAIAA
          time_range = 3600
          timezone = Europe/Paris
          url = https://claranet-sandbox.signalfx.com/#/detector/E5CaZOnAEAA
          viz_options.# = 1
          viz_options.0.color = orange
          viz_options.0.display_name =
          viz_options.0.label = app delay
          viz_options.0.value_prefix =
          viz_options.0.value_suffix =
          viz_options.0.value_unit = Second

          Dependencies:
            signalfx_team.detectorTeam
        signalfx_team.detectorTeam:
          ID = E5CaatpAIAA
          provider = provider.signalfx
          description = Detector Team
          name = Super Cool Team
          notifications_critical.# = 1
          notifications_critical.0 = Email,test@example.com
          notifications_default.# = 1
          notifications_default.0 = Webhook,,secret,https://www.example.com
          notifications_info.# = 1
          notifications_info.0 = Webhook,,secret,https://www.example.com/2
          notifications_major.# = 1
          notifications_major.0 = Webhook,,secret,https://www.example.com/3
          notifications_minor.# = 1
          notifications_minor.0 = Webhook,,secret,https://www.example.com/4
          notifications_warning.# = 1
          notifications_warning.0 = Webhook,,secret,https://www.example.com/5
          url = https://claranet-sandbox.signalfx.com/#/team/E5CaatpAIAA
--- FAIL: TestAccCreateUpdateDetector (3.74s)
FAIL
FAIL    github.com/splunk-terraform/terraform-provider-signalfx/signalfx        3.754s
?       github.com/splunk-terraform/terraform-provider-signalfx/version [no test files]
FAIL
make: *** [GNUmakefile:17: testacc] Error 1
```

```
make testacc TESTARGS='-run=TestAccCreateUpdateDetector -count=1'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccCreateUpdateDetector -count=1 -timeout 120m
?       github.com/splunk-terraform/terraform-provider-signalfx [no test files]
=== RUN   TestAccCreateUpdateDetector
--- PASS: TestAccCreateUpdateDetector (6.93s)
PASS
ok      github.com/splunk-terraform/terraform-provider-signalfx/signalfx        6.943s
?       github.com/splunk-terraform/terraform-provider-signalfx/version [no test files]
```

**Comment by pdecat** [comment]
Apparently, the unstable behavior is caused by the API:



First POST request is ok:
```
2021/06/29 11:33:47 [DEBUG] SignalFx API Request Details:
---[ REQUEST ]---------------------------------------
POST /v2/detector HTTP/1.1
Host: api.eu0.signalfx.com
User-Agent: Terraform/0.12.7-sdk terraform-provider-signalfx/dev
{
...
 "tags": [
  "tag-2",
  "tag-1"
 ],
...
```
```
2021/06/29 11:33:48 [DEBUG] SignalFx API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store, must-revalidate, no-transform
Content-Type: application/json
Date: Tue, 29 Jun 2021 09:33:47 GMT
...
{
...
  "id" : "E5ChRtPAIAA",
...
  "tags" : [ "tag-1", "tag-2" ],
...
```

But subsequent read only returns one tag:
```
2021/06/29 11:33:49 [DEBUG] SignalFx API Request Details:
---[ REQUEST ]---------------------------------------
GET /v2/detector/E5ChRtPAIAA HTTP/1.1
Host: api.eu0.signalfx.com
User-Agent: Terraform/0.12.7-sdk terraform-provider-signalfx/dev
...
```
```
2021/06/29 11:33:49 [DEBUG] SignalFx API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store, must-revalidate, no-transform
Content-Type: application/json
Date: Tue, 29 Jun 2021 09:33:49 GMT
...
{
...
  "id" : "E5ChRtPAIAA",
...
  "tags" : [ "tag-2" ],
...
}
```

**Comment by xp-1000** [comment]
@pdecat is right. impossible to reproduce in real situation with terraform apply/plan commands but the acceptances tests probably run the read faster just after the post and the API returns a not yet up to date response which cause the diff sometimes.

**Comment by xp-1000** [comment]
Adding a sleep of 1s in the code for detector updating/creation allows to make the acceptance tests passing **always**.

For creation of 378 detectors it increases the execution time from 1m10s to 1m45s in my environment.

**Comment by xp-1000** [comment]
Hello @jrcamp @keitwb @asuresh4

can we have your opinion on this PR ?

thanks

**Review by jrcamp — APPROVED** [review]

**Comment by jrcamp** [comment]
Yeah unfortunately there are stale reads from server. :( Thanks for the tags fix.

**Pull request merged**
