### PR TITLE
Added timezone argument to set Calendar Window Time Zone in list and …

### PR DESCRIPTION
**Pull request by rajeshkurup**
…heatmap charts

### CODE REVIEW

**Comment by jrcamp** [comment]
Thanks for adding. Can you update docs and rebase changelog.md? (I forgot to push last release changelog.md changes to main until just now)

**Comment by rajeshkurup** [comment]
@jrcamp Hi, changelog has been updated. Please review.

**Comment by jrcamp** [comment]
Thanks, I was also referring to these docs: https://github.com/splunk-terraform/terraform-provider-signalfx/blob/35ee7b5e850aefe927b72a8111481ba9438b7275/website/docs/r/list_chart.html.markdown and https://github.com/splunk-terraform/terraform-provider-signalfx/blob/36303dc3e6cc1e6a937aa9f408dcb8291afeba40/website/docs/r/heatmap_chart.html.markdown

**Comment by rajeshkurup** [comment]
@jrcamp updated those docs as well - sorry, I was not aware of them

**Review by jrcamp — APPROVED** [review]

**Comment by jrcamp** [comment]
@rajeshkurup Thanks, do you need a release made?

**Comment by rajeshkurup** [comment]
@jrcamp yes, please release it - I've a bug to fix on our side

**Comment by jrcamp** [comment]
released, may take a few minutes to show up on registry.

**Comment by rajeshkurup** [comment]
@jrcamp thanks a lot!

**Pull request merged**
