### PR TITLE
FEAT: add and update resource_gcp_integration fields

### PR DESCRIPTION
**Pull request by Moon1706**
Issue: https://github.com/splunk-terraform/terraform-provider-signalfx/issues/411
Wait approve: https://github.com/signalfx/signalfx-go/pull/180

### CODE REVIEW

**Comment by Moon1706** [comment]
@keitwb
PR is ready. https://github.com/signalfx/signalfx-go/pull/180 have added changes.

**Comment by bgola-signalfx** [comment]
Thank you @Moon1706 for your contribution! We will review your changes this week.

**Review by bgola-signalfx — APPROVED** [review]

**Comment by gtrog** [comment]
Heads up, this is a breaking change that causes issues with upgrading to newer *minor* version of the provider:

```
│ Error: Failed to decode resource from state
│ 
│ Error decoding "signalfx_gcp_integration.gcp" from previous state: unsupported attribute "whitelist"
```

There should ideally be a temporary fallback while this is being deprecated.

**Comment by akonarska** [comment]
@gtrog Thanks for bringing this to our attention! Sorry that we missed your comment, the fix will be released today to fix that incompatibility.

**Pull request merged**
