### PR TITLE
Support event publish label options

### LINKED ISSUE #61: EventPublishLabelOptions structure is not supported
As example, I have a config like this:
```
resource "signalfx_time_chart" "sfx-EBq0cWjAAAA" {
............cut start.............
  viz_options               = [{ display_name = "gitlab.deployment", label = "A", value_prefix = "", value_suffix = "" }, { display_name = "gitlab.deployment", label = "C", value_prefix = "", value_suffix = "" }, { display_name = "gitlab.deployment", label = "D", value_prefix = "", value_suffix = "" }, { display_name = "gitlab.deployment", label = "B" }, { color = "orange", display_name = "gitlab.deployment", label = "F" }]
  program_text              = <<EOF
A = data('gitlab.deployment', filter=filter('application_name', 'carspt') and filter('status', 'succeed'), rollup='sum').publish(label='A')
C = data('gitlab.deployment', filter=filter('application_name', 'autovitro') and filter('status', 'succeed'), rollup='sum').publish(label='C')
D = data('gitlab.deployment', filter=filter('application_name', 'otomotopl') and filter('status', 'succeed'), rollup='sum').publish(label='D')
B = events(eventType='gitlab.deployment', filter=filter('application_name', 'carspt') and filter('status', 'succeed')).publish(label='B')
F = events(eventType='gitlab.deployment', filter=filter('type', 'redeploy') and filter('status', 'succeed')).publish(label='F')
EOF
...........cut end................
}
```
after applying, I receive error:

```
Error: Error applying plan:
1 error(s) occurred:
* signalfx_time_chart.sfx-EBq0cWjAAAA: 1 error(s) occurred:
* signalfx_time_chart.sfx-EBq0cWjAAAA: Unexpected status code: 400: {
  "code" : 400,
  "message" : "Label \"F\" defined in publish options was not found in any publish block in the program text."
}
``` 

I did grep all repo recursively and figured out that terraform provider doesn't process the structure, like `PublishLabelOptions`
Seems that **events** labels are not supported yet, but maybe I am doing smth wrong?

### PR DESCRIPTION
**Pull request by cory-signalfx**
# Summary

Adds `event_options` to support event publish label options.

# Motivation

Fixes #61

### CODE REVIEW

**Comment by cory-signalfx** [comment]
Holding on to this for some internal discussions, as there may be changes forthcoming.

**Comment by cory-signalfx** [comment]
Got confirmation we're good here!

**Comment by doctornkz** [comment]
Please, take a look. 

I create that config:
```
resource "signalfx_time_chart" "sfx-EAu7r6kAIAA" {
  name              = "Cars deployment count event"
  description       = ""
  plot_type         = "ColumnChart"
  stacked           = false
  axes_include_zero = true
  histogram_options {
    color_theme = "red"
  }
  legend_options_fields {
    property = "application_name"
    enabled  = true
  }
  legend_options_fields {
    property = "environment"
    enabled  = false
  }
  legend_options_fields {
    property = "sf_metric"
    enabled  = true
  }
  viz_options               = []
  event_options             = [{ display_name = "Deployment event", label = "Deployment event" }]
  program_text              = <<EOF
A = events(eventType='deployment', filter=filter('category', 'cars')).count(by=['application_name','environment']).publish()
B = events(eventType='deployment', filter=filter('category', 'cars')).publish(label='Deployment event')

EOF
  disable_sampling          = false
  minimum_resolution        = 0
  unit_prefix               = "Metric"
  max_delay                 = 0
  color_by                  = "Dimension"
  on_chart_legend_dimension = "application_name"
  time_range                = 604800
}
```
after applying I receive error:
```
Error: signalfx_time_chart.sfx-EAu7r6kAIAA: : invalid or unknown key: event_options
```
I am using the provider from upstream, maybe it's not released yet?

**Comment by cory-signalfx** [comment]
Sorry, I haven't released this yet. I generally wait for the end of the week to let bugs shake out or collect other features first. Lemme get a release ready!

**Comment by doctornkz** [comment]
No problem, man! No sorry, dont worry. I will wait.)

**Comment by cory-signalfx** [comment]
All good, I asked HashiCorp for a release so we should get one a bit later today. I'm out later this week anyway. :)

**Pull request merged**
